version: "3.2"

services: 
    app:
        image: breakingapp:v1 
        container_name: appScrapper
        ports: 
            - '5050'
        links: 
            - db
    db:
        image: mysql
        container_name: appDB
        restart: always
        ports: 
            - 6063:3306
        environment:
            MYSQL_ROOT_PASSWORD: admin1
    
    phpmyadmin:
        depends_on: 
            - db
        image: phpmyadmin/phpmyadmin
        container_name: myadmin
        restart: always
        ports:
          - 8080:80
        environment:
            PMA_HOST: db
        

    